---
kind: pipeline
type: docker
name: frontend_deploy

platform:
  os: linux
  arch: amd64

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: whitelist
    host:
      path: /etc/docker/daemon.json
  - name: consul-template
    host:
      path: /usr/bin/consul-template

steps:
  - name: build
    pull: if-not-exists
    image: node:13.6.0
    commands:
      - npm install
      - npm run build

  - name: deploy
    pull: if-not-exists
    image: docker
    volumes:
      - name: whitelist
        path: /etc/docker/daemon.json
      - name: dockersock
        path: /var/run/docker.sock
      - name: consul-template
        path: /usr/bin/consul-template
    commands:
      - consul-template -consul-addr="consul.ujunglangit.id:8500" -template="config/consul/config.ctmpl:config/out.env" -log-level debug  -once
      - docker build -t dialoegue_vendor_web .
      - docker tag dialoegue_vendor_web 45.32.110.149:5000/dialoegue_vendor_web:latest
      - docker push 45.32.110.149:5000/dialoegue_vendor_web:latest

  - name: reload
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host
      username:
        from_secret: uname
      password:
        from_secret: deploypass
      port: 22
      script:
        - docker stop dialoegue_vendor_web
        - docker rm dialoegue_vendor_web
        - docker rmi 45.32.110.149:5000/dialoegue_vendor_web
        - docker pull 45.32.110.149:5000/dialoegue_vendor_web:latest
        - docker run -d --name dialoegue_vendor_web -p 45.32.110.149:15000:5000 -v /etc/localtime:/etc/localtime:ro  45.32.110.149:5000/dialoegue_vendor_web
